-- Snapshot dữ liệu THẬT của news.sources tại 2026-08-15 (36 nguồn) — dùng để khôi phục đúng
-- trạng thái đang hoạt động khi deploy sang máy khác. Migration 0005/0008/0010/0013 KHÔNG đủ
-- (không có bản vá URL csa-iot-newsroom, không có nguồn "thv" thêm tay qua UI) — dùng file
-- này để bù drift đó. Chạy SAU KHI đã áp dụng hết migration 0001-0015 (tạo schema xong).
-- File tự TRUNCATE trước khi insert nên chạy lại nhiều lần vẫn an toàn (idempotent).
--
-- PostgreSQL database dump
--


-- Dumped from database version 17.10 (Debian 17.10-1.pgdg12+1)
-- Dumped by pg_dump version 17.10 (Debian 17.10-1.pgdg12+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
TRUNCATE news.sources RESTART IDENTITY CASCADE;
-- Data for Name: sources; Type: TABLE DATA; Schema: news; Owner: registry_admin
--

INSERT INTO news.sources (id, slug, name, kind, url, extract_rule, lang, region, category, tier, fetch_cron, requires_js, enabled, notes, created_at) VALUES (2, 'knxhub-dali-d4i-smart-luminaires', 'KNXHub — DALI D4i Smart Luminaires', 'manual', 'https://www.knxhub.com/dali-d4i-smart-luminaires/', '{}', 'en', 'global', 'media', 2, '0 */6 * * *', false, true, 'Energy monitoring tới từng luminaire, predictive maintenance', '2026-08-14 06:48:52.416754+00');
INSERT INTO news.sources (id, slug, name, kind, url, extract_rule, lang, region, category, tier, fetch_cron, requires_js, enabled, notes, created_at) VALUES (3, 'knxhub-advanced-dali-energy-management', 'KNXHub — Advanced DALI Energy Management', 'manual', 'https://www.knxhub.com/advanced-dali-energy-management/', '{}', 'en', 'global', 'media', 2, '0 */6 * * *', false, true, 'Daylight harvesting, occupancy scheduling, energy dashboard', '2026-08-14 06:48:52.416754+00');
INSERT INTO news.sources (id, slug, name, kind, url, extract_rule, lang, region, category, tier, fetch_cron, requires_js, enabled, notes, created_at) VALUES (4, 'electropages-dali2-controller-2025', 'Electropages — New Controller Makes DALI-2 Accessible', 'manual', 'https://www.electropages.com/2025/10/new-controller-makes-dali-2-accessible-every-lighting-project', '{}', 'en', 'global', 'media', 2, '0 */6 * * *', false, true, 'Tin sản phẩm controller DALI-2 mới (10/2025)', '2026-08-14 06:48:52.416754+00');
INSERT INTO news.sources (id, slug, name, kind, url, extract_rule, lang, region, category, tier, fetch_cron, requires_js, enabled, notes, created_at) VALUES (5, 'tillumelight-d4i-dali2-data-management', 'TILLUME — D4i & DALI-2 LED Data Management', 'manual', 'https://tillumelight.com/en/blogs/dali-2-series/d4i-dali-2-intelligent-lighting-data-management', '{}', 'en', 'global', 'manufacturer', 2, '0 */6 * * *', false, true, 'D4i vs DALI-2 phân biệt rõ, IEC 62386-251', '2026-08-14 06:48:52.416754+00');
INSERT INTO news.sources (id, slug, name, kind, url, extract_rule, lang, region, category, tier, fetch_cron, requires_js, enabled, notes, created_at) VALUES (6, 'businesswatchgroup-en50131-guide', 'Business Watch Group — EN50131 Guide', 'manual', 'https://www.businesswatchgroup.co.uk/en50131-guide-intruder-alarm-grades-made-simple/', '{}', 'en', 'UK', 'media', 2, '0 */6 * * *', false, true, 'Grade 1-4 ngắn gọn — tham khảo bài cho ME contractor', '2026-08-14 06:48:52.416754+00');
INSERT INTO news.sources (id, slug, name, kind, url, extract_rule, lang, region, category, tier, fetch_cron, requires_js, enabled, notes, created_at) VALUES (7, 'euro-security-satel-expo-berlin-2025', 'Euro Security DE — Satel tại Security Expo Berlin 2025', 'manual', 'https://euro-security.de/en/integrated-security-and-automation-solutions-from-satel-at-security-expo-berlin-2025/', '{}', 'en', 'DE', 'media', 2, '0 */6 * * *', false, true, 'Tin ngành, sản phẩm mới building automation', '2026-08-14 06:48:52.416754+00');
INSERT INTO news.sources (id, slug, name, kind, url, extract_rule, lang, region, category, tier, fetch_cron, requires_js, enabled, notes, created_at) VALUES (8, 'intelibus-satel-int-knx-2', 'Intelibus UK — Satel INT-KNX-2 Integration Module', 'manual', 'https://intelibus.co.uk/product/satel-integration-module-for-integra-panel-and-knx-automation-system/', '{}', 'en', 'UK', 'distributor', 2, '0 */6 * * *', false, true, 'Tích hợp INTEGRA + KNX — bài cho SI cần ghép 2 hệ', '2026-08-14 06:48:52.416754+00');
INSERT INTO news.sources (id, slug, name, kind, url, extract_rule, lang, region, category, tier, fetch_cron, requires_js, enabled, notes, created_at) VALUES (9, 'freewaves-satel-smart-security', 'FreeWaves — Satel Smart Security Systems', 'manual', 'https://www.freewaves.com.cy/satel-smart-security-systems-the-next-generation-of-protection-for-homes-and-businesses/', '{}', 'en', 'CY', 'distributor', 3, '0 */6 * * *', false, true, 'Góc nhìn partner/distributor, INTEGRA cho commercial', '2026-08-14 06:48:52.416754+00');
INSERT INTO news.sources (id, slug, name, kind, url, extract_rule, lang, region, category, tier, fetch_cron, requires_js, enabled, notes, created_at) VALUES (10, 'makel-knx-2026-update-scenarios', 'Makel — 2026 Update on KNX Systems: 7 Scenarios', 'manual', 'https://www.makel.com.tr/en/blog/smart-home-technologies/2026-update-on-knx-systems-7-most-demanded-scenarios-in-homes-and-offices', '{}', 'en', 'TR', 'manufacturer', 2, '0 */6 * * *', false, true, '7 kịch bản KNX thực tế phổ biến nhất', '2026-08-14 06:48:52.416754+00');
INSERT INTO news.sources (id, slug, name, kind, url, extract_rule, lang, region, category, tier, fetch_cron, requires_js, enabled, notes, created_at) VALUES (11, 'knxman-knx-2025-top-trends', 'KNXMAN — KNX in 2025: Top Trends', 'manual', 'https://knxman.com/2025/04/03/knx-in-2025-top-trends-driving-smart-building-innovation/', '{}', 'en', 'global', 'media', 2, '0 */6 * * *', false, true, 'KNX Secure, IoT, AI, sustainability — tổng hợp xu hướng 2025', '2026-08-14 06:48:52.416754+00');
INSERT INTO news.sources (id, slug, name, kind, url, extract_rule, lang, region, category, tier, fetch_cron, requires_js, enabled, notes, created_at) VALUES (12, 'msselectronics-bms-knx-energy-costs', 'MSS Electronics — BMS & KNX Reduce Energy Costs', 'manual', 'https://msselectronics.gr/en/smart-buildings-reduce-energy-costs/', '{}', 'en', 'GR', 'distributor', 3, '0 */6 * * *', false, true, 'Bài tư vấn ROI cho chủ đầu tư', '2026-08-14 06:48:52.416754+00');
INSERT INTO news.sources (id, slug, name, kind, url, extract_rule, lang, region, category, tier, fetch_cron, requires_js, enabled, notes, created_at) VALUES (13, 'detaillighting-casambi-specifiers', 'Detail Lighting UK — Casambi Scene Setting for Specifiers', 'manual', 'https://detaillighting.co.uk/lighting-controls-explained-casambi-scene-setting-and-what-specifiers-need-to-know/', '{}', 'en', 'UK', 'distributor', 2, '0 */6 * * *', false, true, 'So sánh Casambi vs DALI, scene control, tender spec', '2026-08-14 06:48:52.416754+00');
INSERT INTO news.sources (id, slug, name, kind, url, extract_rule, lang, region, category, tier, fetch_cron, requires_js, enabled, notes, created_at) VALUES (14, 'casambi-us-hospitality', 'Casambi US — Hospitality Use Case', 'manual', 'https://casambi.us/hospitality/', '{}', 'en', 'US', 'manufacturer', 1, '0 */6 * * *', false, true, 'Use case khách sạn/nhà hàng, chính chủ Casambi', '2026-08-14 06:48:52.416754+00');
INSERT INTO news.sources (id, slug, name, kind, url, extract_rule, lang, region, category, tier, fetch_cron, requires_js, enabled, notes, created_at) VALUES (15, 'casambi-specification-guide', 'Casambi — Specification Guide (Tender Text)', 'manual', 'https://casambi.com/specification-with-casambi/', '{}', 'en', 'global', 'manufacturer', 1, '0 */6 * * *', false, true, 'Tender text chuẩn, dùng khi tư vấn ME contractor/specifier', '2026-08-14 06:48:52.416754+00');
INSERT INTO news.sources (id, slug, name, kind, url, extract_rule, lang, region, category, tier, fetch_cron, requires_js, enabled, notes, created_at) VALUES (16, 'sohu-smart-lighting-industry-insight-2026', '搜狐 — 2026年智能照明控制系统行业洞察', 'manual', 'https://www.sohu.com/a/1051913121_122155969', '{}', 'zh', 'CN', 'media', 2, '0 */6 * * *', false, true, 'KNX vs hệ thống TQ, DALI gateway thị trường', '2026-08-14 06:48:52.416754+00');
INSERT INTO news.sources (id, slug, name, kind, url, extract_rule, lang, region, category, tier, fetch_cron, requires_js, enabled, notes, created_at) VALUES (17, 'sohu-knx-dali-gateway-integration', '搜狐 — 智能楼宇KNX与DALI协议融合网关', 'manual', 'https://www.sohu.com/a/958742372_121681516', '{}', 'zh', 'CN', 'media', 2, '0 */6 * * *', false, true, 'Kiến trúc phần mềm/phần cứng gateway KNX-DALI', '2026-08-14 06:48:52.416754+00');
INSERT INTO news.sources (id, slug, name, kind, url, extract_rule, lang, region, category, tier, fetch_cron, requires_js, enabled, notes, created_at) VALUES (18, 'sohu-knx-dali-lighting-application', '搜狐 — 浅谈智能照明系统KNX与DALI协议网关的应用', 'manual', 'https://www.sohu.com/a/734721093_121248877', '{}', 'zh', 'CN', 'media', 3, '0 */6 * * *', false, true, 'Ứng dụng gateway KNX-DALI trong chiếu sáng thông minh', '2026-08-14 06:48:52.416754+00');
INSERT INTO news.sources (id, slug, name, kind, url, extract_rule, lang, region, category, tier, fetch_cron, requires_js, enabled, notes, created_at) VALUES (19, 'samsung-research-matter-1-6-release', 'Samsung Research — CSA Matter 1.6 Release', 'manual', 'https://research.samsung.com/blog/CSA-Matter-1-6-Release-Ambient-Sensing-More-Intuitive-Setup-Multi-Ecosystem-Experiences-and-Context-Driven-Control', '{}', 'en', 'global', 'manufacturer', 1, '0 */6 * * *', false, true, 'Chi tiết kỹ thuật chính thức Matter 1.6, nguồn uy tín cao', '2026-08-14 06:48:52.416754+00');
INSERT INTO news.sources (id, slug, name, kind, url, extract_rule, lang, region, category, tier, fetch_cron, requires_js, enabled, notes, created_at) VALUES (20, 'matterhubs-best-matter-hubs-2026', 'Matterhubs — 10 Best Matter Supported Smart Hubs 2026', 'manual', 'https://blog.matterhubs.com/matter-hubs/', '{}', 'en', 'global', 'media', 2, '0 */6 * * *', false, true, 'Đối thủ content trực tiếp — dùng đối chiếu "Matter vs KNX"', '2026-08-14 06:48:52.416754+00');
INSERT INTO news.sources (id, slug, name, kind, url, extract_rule, lang, region, category, tier, fetch_cron, requires_js, enabled, notes, created_at) VALUES (21, 'matterhubs-tapo-smart-plug-mini', 'Matterhubs — Tapo Smart Plug Mini (Matter)', 'manual', 'https://blog.matterhubs.com/tapo-smart-plug-mini/', '{}', 'en', 'global', 'media', 3, '0 */6 * * *', false, true, 'Review sản phẩm entry-level', '2026-08-14 06:48:52.416754+00');
INSERT INTO news.sources (id, slug, name, kind, url, extract_rule, lang, region, category, tier, fetch_cron, requires_js, enabled, notes, created_at) VALUES (22, 'matterhubs-evehome-matter-devices', 'Matterhubs — Matter Compatible EveHome Devices', 'manual', 'https://blog.matterhubs.com/evehome-matter-devices/', '{}', 'en', 'global', 'media', 3, '0 */6 * * *', false, true, 'Review dòng thiết bị EveHome', '2026-08-14 06:48:52.416754+00');
INSERT INTO news.sources (id, slug, name, kind, url, extract_rule, lang, region, category, tier, fetch_cron, requires_js, enabled, notes, created_at) VALUES (23, 'thinkrobotics-matter-protocol-guide-2025', 'ThinkRobotics — Matter Protocol Explained: Complete Guide 2025', 'manual', 'https://thinkrobotics.com/blogs/learn/matter-protocol-explained-for-smart-homes-complete-guide-2025', '{}', 'en', 'global', 'media', 2, '0 */6 * * *', false, true, 'Bài giải thích Matter toàn diện cho B2C', '2026-08-14 06:48:52.416754+00');
INSERT INTO news.sources (id, slug, name, kind, url, extract_rule, lang, region, category, tier, fetch_cron, requires_js, enabled, notes, created_at) VALUES (27, 'androidcentral-smart-home', 'Android Central — Smart Home', 'html_list', 'https://www.androidcentral.com/accessories/smart-home', '{"list_selector": "article.search-result"}', 'en', 'global', 'media', 2, '0 */6 * * *', true, true, 'Thiên hệ sinh thái Google Home/Gemini — LƯU Ý: card không có <a href> trong static HTML, cần Playwright (B6) để lấy link thật, selector chưa verify qua JS-rendered DOM.', '2026-08-14 06:48:52.416754+00');
INSERT INTO news.sources (id, slug, name, kind, url, extract_rule, lang, region, category, tier, fetch_cron, requires_js, enabled, notes, created_at) VALUES (1, 'knxhub-dali-lighting-control-protocol', 'KNXHub — DALI Lighting Control Protocol Explained', 'manual', 'https://www.knxhub.com/dali-lighting-control-protocol-and-future-explained/', '{}', 'en', 'global', 'media', 2, '0 */6 * * *', false, true, 'DALI-1 → DALI-2 → D4i → IoT-ready, bài explainer toàn diện', '2026-08-14 06:48:52.416754+00');
INSERT INTO news.sources (id, slug, name, kind, url, extract_rule, lang, region, category, tier, fetch_cron, requires_js, enabled, notes, created_at) VALUES (28, 'engadget-smart-home-reviews', 'Engadget — Smart Home Reviews', 'html_list', 'https://www.engadget.com/category/smart-home-reviews/', '{"card_selector": "article.article-block", "link_selector": "h3 a"}', 'en', 'global', 'media', 2, '0 */6 * * *', false, true, 'Độ phủ thấp (review thưa) — theo dõi thêm trước khi tăng tier', '2026-08-14 06:48:52.416754+00');
INSERT INTO news.sources (id, slug, name, kind, url, extract_rule, lang, region, category, tier, fetch_cron, requires_js, enabled, notes, created_at) VALUES (30, 'home-assistant-blog', 'Home Assistant — Blog', 'html_list', 'https://www.home-assistant.io/blog/', '{"date_attr": "datetime", "card_selector": "article.listing", "date_selector": "time", "link_selector": "h1 a", "page_url_template": "https://www.home-assistant.io/blog/posts/{n}"}', 'en', 'global', 'community', 1, '0 */6 * * *', false, true, 'Nguồn chính thức open-source ecosystem, độ tin cậy cao', '2026-08-14 06:48:52.416754+00');
INSERT INTO news.sources (id, slug, name, kind, url, extract_rule, lang, region, category, tier, fetch_cron, requires_js, enabled, notes, created_at) VALUES (33, 'matter-smarthome-de-development', 'Matter Smarthome DE — Development', 'html_list', 'https://matter-smarthome.de/en/development/', '{"card_selector": "article.post", "date_selector": "span.published", "link_selector": "h2 a", "page_url_template": "https://matter-smarthome.de/en/development/page/{n}/"}', 'en', 'DE', 'media', 2, '0 */6 * * *', false, true, 'Roadmap Matter, gồm bài KNX IoT + Matter integration. Gộp page/3,4,5 vào đây — chỉ theo dõi 1 feed', '2026-08-14 06:48:52.416754+00');
INSERT INTO news.sources (id, slug, name, kind, url, extract_rule, lang, region, category, tier, fetch_cron, requires_js, enabled, notes, created_at) VALUES (32, 'matter-smarthome-de-practice', 'Matter Smarthome DE — Practice', 'html_list', 'https://matter-smarthome.de/en/practice/', '{"card_selector": "article.post", "date_selector": "span.published", "link_selector": "h2 a"}', 'en', 'DE', 'media', 2, '0 */6 * * *', false, true, 'Hướng dẫn thực hành Matter (tác giả Frank-Oliver Grün)', '2026-08-14 06:48:52.416754+00');
INSERT INTO news.sources (id, slug, name, kind, url, extract_rule, lang, region, category, tier, fetch_cron, requires_js, enabled, notes, created_at) VALUES (34, 'smartthings-blog-matter', 'SmartThings Blog — Category: Matter', 'html_list', 'https://blog.smartthings.com/category/matter/', '{"card_selector": "div.featured_post, div.right", "date_selector": "div.time", "link_selector": "div.post_title h4 a"}', 'en', 'global', 'manufacturer', 2, '0 */6 * * *', false, true, 'Nguồn chính thức Samsung, thiên marketing hệ sinh thái', '2026-08-14 06:48:52.416754+00');
INSERT INTO news.sources (id, slug, name, kind, url, extract_rule, lang, region, category, tier, fetch_cron, requires_js, enabled, notes, created_at) VALUES (29, 'staceyoniot-smart-home-tag', 'Stacey on IoT — Smart Home tag', 'html_list', 'https://staceyoniot.com/tag/smart-home/', '{"card_selector": "article.post", "date_selector": "time.entry-time", "link_selector": "h2 a", "page_url_template": "https://staceyoniot.com/tag/smart-home/page/{n}/"}', 'en', 'global', 'media', 1, '0 */6 * * *', false, true, 'Phân tích IoT chuyên sâu, chất lượng kỹ thuật tốt', '2026-08-14 06:48:52.416754+00');
INSERT INTO news.sources (id, slug, name, kind, url, extract_rule, lang, region, category, tier, fetch_cron, requires_js, enabled, notes, created_at) VALUES (25, 'the-ambient-news-matter', 'The Ambient — News: Matter', 'html_list', 'https://www.the-ambient.com/news/matter/', '{"date_attr": "datetime", "card_selector": "article.l-post", "date_selector": "time.post-date", "link_selector": "h2 a", "page_url_template": "https://www.the-ambient.com/news/matter/page/{n}/"}', 'en', 'UK', 'media', 1, '0 */6 * * *', false, true, 'Feed tin Matter chuyên biệt — giá trị nhất nhóm The Ambient', '2026-08-14 06:48:52.416754+00');
INSERT INTO news.sources (id, slug, name, kind, url, extract_rule, lang, region, category, tier, fetch_cron, requires_js, enabled, notes, created_at) VALUES (24, 'the-ambient-news-smart-home', 'The Ambient — News: Smart Home', 'html_list', 'https://www.the-ambient.com/news/smart-home/', '{"date_attr": "datetime", "card_selector": "article.l-post", "date_selector": "time.post-date", "link_selector": "h2 a", "page_url_template": "https://www.the-ambient.com/news/smart-home/page/{n}/"}', 'en', 'UK', 'media', 1, '0 */6 * * *', false, true, 'Feed tin nhanh đa hãng (Google/Apple/Philips/Amazon)', '2026-08-14 06:48:52.416754+00');
INSERT INTO news.sources (id, slug, name, kind, url, extract_rule, lang, region, category, tier, fetch_cron, requires_js, enabled, notes, created_at) VALUES (26, 'the-ambient-reviews', 'The Ambient — Reviews', 'html_list', 'https://www.the-ambient.com/reviews/', '{"date_attr": "datetime", "card_selector": "article.l-post", "date_selector": "time.post-date", "link_selector": "h2 a", "page_url_template": "https://www.the-ambient.com/reviews/page/{n}/"}', 'en', 'UK', 'media', 1, '0 */6 * * *', false, true, 'Reviews thiết bị smart home đã kiểm chứng', '2026-08-14 06:48:52.416754+00');
INSERT INTO news.sources (id, slug, name, kind, url, extract_rule, lang, region, category, tier, fetch_cron, requires_js, enabled, notes, created_at) VALUES (35, 'aqara-blog', 'Aqara — Blog', 'html_list', 'https://www.aqara.com/en/blog/', '{"card_selector": "div.uael-post-wrapper", "date_selector": "span.uael-post__date", "link_selector": "h3 a"}', 'en', 'global', 'manufacturer', 1, '0 */6 * * *', false, true, 'Case study quy mô lớn (KAFD 10.000+ devices) hữu ích B2B lẫn B2C', '2026-08-14 06:48:52.416754+00');
INSERT INTO news.sources (id, slug, name, kind, url, extract_rule, lang, region, category, tier, fetch_cron, requires_js, enabled, notes, created_at) VALUES (31, 'csa-iot-newsroom', 'CSA IoT — Newsroom', 'html_list', 'https://csa-iot.org/newsroom/', '{"card_selector": "article.hentry.post", "date_selector": "p.entry-date", "link_selector": "a", "page_url_template": "https://csa-iot.org/newsroom/page/{n}/"}', 'en', 'global', 'standard_body', 1, '0 */6 * * *', false, true, 'Nguồn chính thức uy tín nhất cho tin chuẩn Matter — URL đã sửa từ /page/4/ (lỗi từ data gốc, trỏ nhầm trang cũ) về trang mới nhất; selector đổi sang lấy anchor đầu tiên mỗi article vì bài featured/đầu trang không có <a> trong h3.entry-title như các bài sau', '2026-08-14 06:48:52.416754+00');
INSERT INTO news.sources (id, slug, name, kind, url, extract_rule, lang, region, category, tier, fetch_cron, requires_js, enabled, notes, created_at) VALUES (36, 'thv', 'The Verge — Apple', 'html_list', 'https://www.theverge.com/apple', '{"date_attr": "datetime", "card_selector": "div.duet--content-cards--content-card", "date_selector": "time", "link_selector": "a"}', 'EN', NULL, 'social', 2, '0 */6 * * *', false, true, NULL, '2026-08-15 06:58:13.319134+00');


--
-- Name: sources_id_seq; Type: SEQUENCE SET; Schema: news; Owner: registry_admin
--

SELECT pg_catalog.setval('news.sources_id_seq', 38, true);


--
-- PostgreSQL database dump complete
--


